# Generated by Django 5.2.5 on 2025-08-11 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='org',
            name='description',
            field=models.TextField(blank=True, default='Default description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
