# Generated by Django 5.2.5 on 2025-08-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orginvite',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
