# Generated by Django 5.2.5 on 2025-08-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0006_site'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='site',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='site',
            name='city',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='site',
            name='contact_role',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='country_code',
            field=models.CharField(default='GB', max_length=2),
        ),
        migrations.AddField(
            model_name='site',
            name='dpo_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='DPO / privacy email'),
        ),
        migrations.AddField(
            model_name='site',
            name='eic_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='essential_service',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('gas', 'Gas'), ('other', 'Other')], default='electricity', max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='network_role',
            field=models.CharField(blank=True, choices=[('generator', 'Generator'), ('transmission', 'Transmission operator'), ('distribution', 'Distribution operator'), ('supplier', 'Supplier'), ('gas_transmission', 'Gas transmission'), ('gas_distribution', 'Gas distribution'), ('storage', 'Storage'), ('lng', 'LNG'), ('other', 'Other')], default='distribution', max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='ooh_phone',
            field=models.CharField(blank=True, max_length=64, verbose_name='Out-of-hours phone'),
        ),
        migrations.AddField(
            model_name='site',
            name='postcode',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=64),
        ),
        migrations.RemoveField(
            model_name='site',
            name='address',
        ),
        migrations.RemoveField(
            model_name='site',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='site',
            name='name',
        ),
        migrations.RemoveField(
            model_name='site',
            name='org',
        ),
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
    ]
