# Generated by Django 5.2.5 on 2025-08-15 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0007_alter_site_options_alter_site_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='site',
            name='address',
            field=models.TextField(
                blank=True,
                help_text='Legacy address (prefer structured fields below).',
            ),
        ),
        migrations.AddField(
            model_name='site',
            name='created_at',
            # Populate existing rows with now; new rows will be auto-set by the model.
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='site',
            name='name',
            # Don't use a datetime default here – give a simple string.
            field=models.CharField(max_length=200, default='(unnamed site)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='site',
            name='org',
            # TEMPORARILY NULLABLE to avoid needing a bogus default during migration.
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sites',
                to='orgs.org',
            ),
        ),
        migrations.AlterField(
            model_name='org',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='site',
            unique_together={('org', 'name')},
        ),
    ]
