# Generated by Django 5.2.5 on 2025-08-13 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentattachment',
            name='incident',
        ),
        migrations.RemoveField(
            model_name='incidentattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='incidentupdate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='incidentupdate',
            name='incident',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='incidents_i_org_id_52e2ce_idx',
        ),
        migrations.RemoveIndex(
            model_name='incident',
            name='incidents_i_org_id_e47bbe_idx',
        ),
        migrations.AlterField(
            model_name='incident',
            name='aware_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='classification',
            field=models.CharField(choices=[('security', 'Security incident'), ('availability', 'Availability / continuity'), ('data', 'Data protection / integrity'), ('other', 'Other')], default='security', max_length=32),
        ),
        migrations.AlterField(
            model_name='incident',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigating', 'Investigating'), ('contained', 'Contained'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=16),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='IncidentAttachment',
        ),
        migrations.DeleteModel(
            name='IncidentUpdate',
        ),
    ]
