# Generated by Django 5.2.5 on 2025-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_remove_incidentattachment_incident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
