# Generated by Django 5.2.5 on 2025-08-14 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0004_incidentattachment_incidentnote'),
        ('orgs', '0006_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incident',
            old_name='description',
            new_name='report_notes',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='incident',
            name='report_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='incident',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='orgs.site'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents_legacy', to='orgs.org'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('reported', 'Reported')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
