# Generated by Django 5.2.5 on 2025-08-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0005_rename_description_incident_report_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='report_notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
