# Generated by Django 5.2.5 on 2025-08-15 08:58

from django.db import migrations
from django.utils import timezone

def forwards(apps, schema_editor):
    Incident = apps.get_model("incidents", "Incident")
    # If status is OPEN, ensure reported_at is NULL
    Incident.objects.filter(status="open").update(reported_at=None)
    # If status is REPORTED but timestamp missing, backfill a sensible one
    qs = Incident.objects.filter(status="reported", reported_at__isnull=True)
    for inc in qs.iterator():
        inc.reported_at = inc.aware_at or inc.created_at or timezone.now()
        inc.save(update_fields=["reported_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0006_alter_incident_report_notes'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
