# Generated by Django 5.2.5 on 2025-08-15 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0007_sync_status_and_reported_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='moderate', max_length=10),
        ),
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.TextField()),
                ('rationale', models.TextField(blank=True, default='')),
                ('privileged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_decisions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='incidents.incident')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(choices=[('OFGEM', 'Ofgem'), ('ICO', 'ICO'), ('CUSTOMERS', 'Customers'), ('INSURER', 'Insurer')], max_length=16)),
                ('deadline_at', models.DateTimeField()),
                ('filed_at', models.DateTimeField(blank=True, null=True)),
                ('submission_ref', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incident')),
            ],
            options={
                'ordering': ('deadline_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='IncidentStakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('commander', 'Incident Commander'), ('tech_lead', 'Technical Lead'), ('comms', 'Comms Lead'), ('legal', 'Legal'), ('dpo', 'DPO'), ('risk', 'Risk/2nd line')], max_length=32)),
                ('required_approver', models.BooleanField(default=False)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stakeholders', to='incidents.incident')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('incident', 'role')},
            },
        ),
    ]
